"""Add location column to jobs table

Revision ID: 9e9fa9364d9e
Revises: 9817be0d64ea
Create Date: 2024-07-06 17:30:50.034730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9fa9364d9e'
down_revision: Union[str, None] = '9817be0d64ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('location', sa.String))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'location')
    # ### end Alembic commands ###
